config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :icms
  resources :cfop
  resources :terceiros
  resources :contas_pag
  resources :vendedores
  resources :contas_rec
  resources :plano_contas
  resources :administradores
  resources :transportadoras
  resources :localizacao_estoques
  resources :movimento_estoques, only: [:index]

  mount Sidekiq::Web => '/sidekiq'

  resources :estoques, only: %i[index show] do
    collection do
      post 'importar'

      scope module: 'estoques' do
        resources :reposicoes, only: %i[new create]
        resources :ajustes, :baixas, only: %i[new create]
      end
    end
  end

  resources :empresas do
    get 'configuracoes', on: :collection
  end
  
  resources :orcamentos do
    resources :orcamento_itens
  end

  resources :nota_fiscais do
    get 'observacoes', on: :member

    resources :gerar_nota_fiscais, only: [:gerar_nota] do
      get 'gerar_nota', on: :collection
    end

    resources :nota_fiscal_itens
    resources :nota_fiscal_duplicatas, only: %i[new create]
  end

  resources :produtos do
    post 'importar', on: :collection
  end

  resources :clientes do
    post 'importar', on: :collection
    get 'observacoes', on: :member

    resources :cliente_contatos
  end

  resources :fornecedores do
    post 'importar', on: :collection
    get 'observacoes', on: :member
  end

  resources :importacoes do
    collection do
      get 'clientes'
      get 'produtos'
      get 'estoques'
      get 'fornecedores'
    end
  end

  root to: 'home#index'

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

  #get "/orcamentos/relatorio", to: "orcamentos#relatorio"  
  #get "/orcamentos/relatorio", to: "orcamento#relatorio" 
  #get "relatorio", to: "orcamento#relatorio"
  #
  #resources :orcamentos
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  belongs_to :empresa
  has_many :contatos, class_name: "ClienteContato", dependent: :delete_all
  has_many :nota_fiscais, dependent: :delete_all

  default_scope { order('nome asc') }

  def self.importar_linha(empresa_id, linha)
    id = 0
    pessoa = 1
    nome = 2
    rg = 3
    cpf = 4
    ie = 5
    cnpj = 6
    endereco = 7
    bairro = 8
    cidade = 9
    uf = 10
    cep = 11
    telefone = 12
    telefone_alternativo = 13
    codcidade_ibge = 14
    telefone_nf = 15
    email = 16
    id_vendedor = 17
    id_terceiro = 18
    empresa_governo = 19

    empresa = Empresa.find(empresa_id)
    cliente = empresa.clientes.new
    cliente.id = linha[id].to_i
    cliente.nome = linha[nome].strip rescue linha[nome]
    cliente.pessoa = linha[pessoa].strip rescue linha[pessoa]
    cliente.cpf = linha[cpf].strip if linha[cpf].to_i != 0
    cliente.rg = linha[rg].strip if linha[rg].to_i != 0
    cliente.cnpj = linha[cnpj] if linha[cnpj].to_i != 0
    cliente.ie = linha[ie] if linha[ie].to_i != 0
    cliente.endereco = linha[endereco].strip rescue linha[endereco] 
    cliente.bairro = linha[bairro].strip rescue linha[bairro]
    cliente.cidade = linha[cidade].strip rescue linha[cidade]
    cliente.cep = linha[cep].strip rescue linha[cep]
    cliente.uf = linha[uf].strip rescue linha[uf]
    cliente.telefone = linha[telefone].strip rescue linha[telefone]  
    cliente.telefone_alternativo = linha[telefone_alternativo].strip rescue linha[telefone_alternativo]  
    cliente.telefone_nf = linha[telefone_nf].strip rescue linha[telefone_nf]
    cliente.email = linha[email].strip rescue linha[email]
    cliente.codcidade_ibge = linha[codcidade_ibge].strip rescue linha[codcidade_ibge]
    cliente.empresa_governo = true if linha[empresa_governo].include?('S')

    vendedor = linha[id_vendedor].to_i
    cliente.vendedor_id = Vendedor.find_or_create_by(id: vendedor, empresa_id: empresa.id).id unless vendedor.zero?
    
    terceiro = linha[id_terceiro].to_i
    cliente.terceiro_id = Terceiro.find_or_create_by(id: terceiro, empresa_id: empresa.id).id unless terceiro.zero?

    cliente.save
  rescue => e
    puts e.to_s
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[show edit update destroy observacoes]
  skip_before_action :verify_authenticity_token, only: [:importar]

  def index
    @clientes = empresa.clientes
    
    if params[:busca].present?
      @clientes = @clientes.where("
        (lower(nome) ilike '%#{params[:busca].downcase}%') OR
        (cpf ilike '%#{params[:busca].downcase}%') OR
        (cnpj ilike '%#{params[:busca].downcase}%')
      ")
    end

    options = { page: params[:page] || 1, per_page: 10 }
    @clientes = @clientes.paginate(options)
  end

  def importar
    if params[:arquivo].blank?
      flash[:error] = 'Selecione um arquivo .CSV'
      redirect_to '/clientes'
      return
    end

    if File.basename(params[:arquivo].tempfile).include?('.CSV')
      dir = Rails.root.join('public', 'uploads')
      Dir.mkdir(dir) unless Dir.exist?(dir)
      @incoming_file = params[:arquivo]
      file_name = "#{rand(34999999)}_file"

      File.open(dir.join(file_name), 'wb') do |file|
        file.write(@incoming_file.read)
      end

      FileImportJob.perform_later(dir.join(file_name).to_s, empresa.id)
    else
      flash[:error] = 'Formato de arquivo não suportado. Selecione um arquivo com a extensão .CSV'
      redirect_to '/clientes'
      return
    end

    flash[:sucesso] = 'Em instantes seus clientes estarão importantes'
    redirect_to '/clientes'
  rescue => e
    flash[:error] = e
    redirect_to '/clientes'
    nil
  end
  
  def observacoes; end

  def show
    if params[:format] == "pdf"
      render pdf: "Cliente id: #{@cliente.id}", 
             template: "clientes/relatorio.pdf.html.erb"
    end
  end
  
  def new
    @cliente = Cliente.new
  end

  def edit; end

  def create
    @cliente = empresa.clientes.build(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_cliente_contatos_path(@cliente)} if params[:contatos].present?
        format.html { redirect_to observacoes_cliente_path(@cliente), notice: 'Cliente Cadastrado' } 
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente Alterado' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente Excluído' }
      format.json { head :no_content }
    end
  end

  private

  def set_cliente
    @cliente = empresa.clientes.find(params[:id])
  end

  def cliente_params
    params.require(:cliente).permit(:vendedor_id, :terceiro_id, :nome, :pessoa, :cpf, :rg, :cnpj, :ie, :endereco, :observacoes, :bairro, :cidade, :cep, :uf, :telefone, :email, :codcidade_ibge, :consumidor_final)
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html (com contato).erb
<%= form_for(@cliente, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @cliente.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h4>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, 'Nome/Razão Social', class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :pessoa, 'Pessoa', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <select class="form-control" name="cliente[pessoa]" id="cliente_pessoa" onclick="verificaPessoa()">
        <option value=""></option>
        <option <% if @cliente.pessoa == 'F' %>selected="selected"<% end %> value="F">FÍSICA</option>
        <option <% if @cliente.pessoa == 'J' %>selected="selected"<% end %> value="J">JURÍDICA</option>
      </select>
    </div>

    <%= f.label :consumidor_final, 'Consumidor Final', class: "col-sm-2 control-label"  %>
    <div class="col-sm-2">
      <%= f.select(:consumidor_final, options_for_select([['NÃO', 'N'], ['SIM', 'S']], :selected => @cliente.consumidor_final), {:include_blank => true}, {class: "form-control"}) %>
    </div>

    <%= f.label :empresa_governo, 'Empresa do Governo', class: "col-sm-2 control-label"  %>
    <div class="col-sm-2">
      <%= f.select(:empresa_governo, options_for_select([['NÃO', false], ['SIM', true]], :selected => @cliente.empresa_governo), {:include_blank => true}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group pessoa-fisica" <% if @cliente.pessoa == 'F' %> style="display: block;" <% else %> style="display: none" <% end %>>
    <%= f.label :cpf, 'CPF', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :cpf, class: "form-control" %>
    </div>
  
    <%= f.label :rg, 'RG', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :rg, class: "form-control" %>
    </div>
  </div>

  <div class="form-group pessoa-juridica" <% if @cliente.pessoa == 'J' %> style="display: block;" <% else %> style="display: none" <% end %>>
    <%= f.label :cnpj, 'CNPJ', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :cnpj, class: "form-control" %>
    </div>
  
    <%= f.label :ie, 'Inscrição Estadual', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :ie, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cep, 'CEP', class: "col-sm-1 control-label" %>
    <div class="col-sm-2">
      <%= f.text_field :cep, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :endereco, 'Endereço', class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :endereco, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :bairro, 'Bairro', class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :bairro, class: "form-control" %>
    </div>
  
    <%= f.label :cidade, 'Cidade', class: "col-sm-1 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :cidade, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :codcidade_ibge, 'Código IBGE', class: "col-sm-1 control-label" %>
    <div class="col-sm-2">
      <%= f.text_field :codcidade_ibge, class: "form-control", disabled: "disable" %>
    </div>

    <%= f.label :uf, 'UF', class: "col-sm-1 control-label" %>
    <div class="col-sm-1">
      <%= f.text_field :uf, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :telefone, 'Telefone', class: "col-sm-1 control-label" %>
    <div class="col-sm-7">
      <%= f.text_field :telefone, class: "form-control" %>
    </div>
  </div>  

  <div class="form-group">
    <%= f.label :email, 'Email', class: "col-sm-1 control-label" %>
    <div class="col-sm-7">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div> 

  <div class="form-group">
    <%= f.label :vendedor, 'Vendedor', class: "col-sm-1 control-label" %>
    <div class="col-sm-5">
      <%= f.select :vendedor_id, Vendedor.all.reorder("nome asc").collect { |vendedor| [vendedor.nome, vendedor.id] }, {:selected => @cliente.vendedor_id, :include_blank => true}, {:class=> 'form-control'} %>
    </div>

    <%= f.label :terceiro, 'Terceiro', class: "col-sm-1 control-label" %>
    <div class="col-sm-5">
      <%= f.select :terceiro_id, Terceiro.all.reorder("nome asc").collect { |terceiro| [terceiro.nome, terceiro.id] }, {:selected => @cliente.terceiro_id, :include_blank => true}, {:class=> 'form-control'} %>
    </div>
  </div>

  <br>
  
  <div>
    <%= link_to "Contatos", "/ruby-book", class:"btn btn-success" %>
  </div>

  //esta linha esta no form origginal
  <div>
    <%= link_to "Contatos", cliente_cliente_contatos_path(@cliente), class:"btn btn-success" %>
  </div>

  <br><br>

  <h4>Contatos</h4>
  <hr>
  <div>
  </div>

  <div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome/Razão Social</th>
        <th>Endereço</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @clientes) do |cliente| %>
        <td><%= cliente.nome %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.bairro %></td>
        <td><%= cliente.cidade %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Apagar', cliente, method: :delete, data: { confirm: 'Confirma ?' } %></td>
      <% end %>
    </tbody>
  </table>
  </div>

  <br><br>

  <h4>Contatos</h4>
  <hr>
  <div id="conteudoContainer">
    <% if @cliente.present? %>
      <% @cliente.contatos.each do |contato| %>
        <div class="item" style="margin-bottom: 40px">
          <div class="form-group">
            <label class="col-sm-2 control-label">Nome</label>
            <div class="col-sm-10">
              <input class="form-control" type="text" value="<%= contato.nome %>" name="cliente[contato][][nome]">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input class="form-control" type="text" value="<%= contato.email %>" name="cliente[contato][][email]">
            </div>
          </div>
          
          <div class="form-group">
            <label class="col-sm-2 control-label">Telefone</label>
            <div class="col-sm-10">
              <input class="form-control" type="text" value="<%= contato.telefone %>" name="cliente[contato][][telefone]">
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Cargo</label>
            <div class="col-sm-4">
              <input class="form-control" type="text" value="<%= contato.cargo %>" name="cliente[contato][][cargo]">
            </div>

            <label class="col-sm-2 control-label">Departamento</label>
            <div class="col-sm-4">
              <input class="form-control" type="text" value="<%= contato.departamento %>" name="cliente[contato][][departamento]">
            </div>
          </div>

        </div>
      <% end %>
    <% end %>

    <div class="item" style="margin-bottom: 40px">
      <div class="form-group">
        <label class="col-sm-2 control-label">Nome</label>
        <div class="col-sm-10">
          <input class="form-control", type="text" name="cliente[contato][][nome]">
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
          <input class="form-control" type="text" name="cliente[contato][][email]">
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Telefone</label>
        <div class="col-sm-10">
          <input class="form-control" type="text" name="cliente[contato][][telefone]">
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Cargo</label>
        <div class="col-sm-4">
          <input class="form-control" type="text" name="cliente[contato][][cargo]">
        </div>

        <label class="col-sm-2 control-label">Departamento</label>
        <div class="col-sm-4">
          <input class="form-control" type="text" name="cliente[contato][][departamento]">
        </div>
      </div>

    </div>
  </div>

  <div class="form-group" style="text-align: right;">
    <a href="javascript:;" onclick="app.contas_pag.mais();" class="btn btn-primary">Mais</a>
  </div>

  <hr>

  <div class="form-group">
    <div class="col-sm-1">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<div id="conteudoContainerTemplate" style="display: none">
  <div class="item" style="margin-bottom: 40px">
    <div class="form-group">
      <label class="col-sm-2 control-label">Nome</label>
      <div class="col-sm-10">
        <input class="form-control" type="text" name="cliente[contato][][nome]">
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Email</label>
      <div class="col-sm-10">
        <input class="form-control" type="text" name="cliente[contato][][email]">
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Telefone</label>
      <div class="col-sm-10">
        <input class="form-control" type="text" name="cliente[contato][][telefone]">
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Cargo</label>
      <div class="col-sm-4">
        <input class="form-control" type="text" name="cliente[contato][][cargo]">
      </div>

      <label class="col-sm-2 control-label">Departamento</label>
      <div class="col-sm-4">
        <input class="form-control" type="text" name="cliente[contato][][departamento]">
      </div>
    </div>

  </div>
</div>

<script>
//Bloqueia a tecla Enter no campo de Input
$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });

  $("#cliente_cpf").mask("000.000.000-00")
  $("#cliente_cnpj").mask("00.000.000/0000-00")
});

const verificaPessoa = () =>{
  const selectElement = document.getElementById("cliente_pessoa")
  var codigo_pessoa = selectElement.value

  if(codigo_pessoa == "F"){
    $('.pessoa-fisica').show()
    $('.pessoa-juridica').hide()
  }else{
    $('.pessoa-fisica').hide()
    $('.pessoa-juridica').show()
  }
}

$("#cliente_endereco").focus(function(){
  let cep = $('#cliente_cep').val()

  $.ajax({
    type: "GET",
    url: "https://viacep.com.br/ws/" + cep + "/json/",
    success: function(data){
      if(data.logradouro){
        $('#cliente_endereco').val(data.logradouro);
        $('#cliente_bairro').val(data.bairro);
        $('#cliente_cidade').val(data.localidade);
        $('#cliente_uf').val(data.uf);
        $('#cliente_codcidade_ibge').val(data.ibge);
      }
    }
  })
});

function formatarCampo(campoTexto) {
    if (campoTexto.value.length <= 11) {
        campoTexto.value = mascaraCpf(campoTexto.value);
    } else {
        campoTexto.value = mascaraCnpj(campoTexto.value);
    }
}
function retirarFormatacao(campoTexto) {
    campoTexto.value = campoTexto.value.replace(/(\.|\/|\-)/g,"");
}
function mascaraCpf(valor) {
    return valor.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/g,"\$1.\$2.\$3\-\$4");
}
function mascaraCnpj(valor) {
    return valor.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/g,"\$1.\$2.\$3\/\$4\-\$5");
}
  
</script>

app/views/clientes/edit.html.erb
<h2>Clientes</h2>

<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @cliente, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h3>Alteração</h3>
</div>

<%= render 'form' %>

app/views/clientes/index.html copy.erb
<h2>Clientes</h2>

<div class="page-header">
  <%= link_to "javascript:window.location.assign('/clientes/new')", class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>

  <h2>Lista</h2>
</div>

<div style="text-align: right; margin-top:10px; margin-bottom:10px">
  <form action="/clientes" method="get">
    <div class="row" style="width:300px;display: inline-block;">
      <div style="float: left">
        <input type="text" name="nome" value="<%=params[:nome] %>" class="form-control" placeholder="Busca..">
      </div>
      <div style="float: left;margin-left:5px">
        <input type="submit" class="btn btn-primary" value="Buscar">
      </div>
    </div>
  </form>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome/Razão Social</th>
        <th>Endereço</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @clientes) do |cliente| %>
        <td><%= cliente.nome %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.bairro %></td>
        <td><%= cliente.cidade %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Apagar', cliente, method: :delete, data: { confirm: 'Confirma ?' } %></td>
      <% end %>
    </tbody>
  </table>

  <div class="apple_pagination">
    <%= will_paginate @clientes, :container => false %>
  </div>
</div>

app/views/clientes/index.html.erb
<h2>Clientes</h2>
<div class="page-header">
  <%= link_to "javascript:window.location.assign('/clientes/new')", class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <h2>Lista</h2>
</div>
<div style="text-align: right; margin-top:10px; margin-bottom:10px">
  <form action="/clientes" method="get">
    <div style="display: flex; justify-content:inherit">
      <input type="text" style="width: 30%; margin-right: 10px;" name="busca" value="<%=params[:busca] %>" class="form-control" placeholder="Busca..">
      <input type="submit" class="btn btn-primary" value="Buscar">
    </div>
  </form>
</div>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Nome/Razão Social</th>
        <th>Endereço</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= content_tag_for(:tr, @clientes) do |cliente| %>
        <td><%= cliente.nome %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.bairro %></td>
        <td><%= cliente.cidade %></td>
        <td><%= link_to 'PDF', cliente_path(cliente, format: :pdf), target: "blank"  %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Apagar', cliente, method: :delete, data: { confirm: 'Confirma ?' } %></td>
      <% end %>
    </tbody>
  </table>
  <div class="apple_pagination">
    <%= will_paginate @clientes, :container => false %>
  </div>
</div>

app/views/clientes/new.html.erb
<h2>Clientes</h2>

<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h2>Inclusão</h2>
</div>

<%= render 'form' %>

app/views/clientes/observacoes.html.erb
<h2>Clientes</h2>
<div class="page-header">
  <%= link_to edit_cliente_path(@cliente), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h2>Observações</h2>
</div>
<%= form_for(@cliente, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @cliente.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h4>
      <ul>
        <% @cliente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-12">
      <%= f.text_area :observacoes, size: '50x10', class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group">
    <div class="col-sm-1">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/clientes/relatorio.pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Viver Saúde PDF</title>
    <meta charset="utf-8">
  </head>
  <body>
    <h2>RELATÓRIO DE CLIENTES</h2>
  </body>
</html>

app/views/clientes/show.html.erb
<h2>Clientes</h2>
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_cliente_path(@cliente), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h2>Mostrar</h2>
</div>
<dl class="dl-horizontal">
  <dt>Nome/Razão Social:</dt>
  <dd><%= @cliente.nome %></dd>
  <dt>Pessoa:</dt>
  <dd><%= @cliente.pessoa %></dd>
  <% if @cliente.pessoa == 'F' %>
    <dt>CPF:</dt>
    <dd><%= @cliente.cpf %></dd>
    <dt>RG:</dt>
    <dd><%= @cliente.rg %></dd>
  <% else %>
    <dt>CNPJ:</dt>
    <dd><%= @cliente.cnpj %></dd>
    <dt>IE:</dt>
    <dd><%= @cliente.ie %></dd>
  <% end %>
  <dt>Endereço:</dt>
  <dd><%= @cliente.endereco %></dd>
  <dt>Bairro:</dt>
  <dd><%= @cliente.bairro %></dd>
  <dt>Cidade:</dt>
  <dd><%= @cliente.cidade %></dd>
  <dt>CEP:</dt>
  <dd><%= @cliente.cep %></dd>
  <dt>UF:</dt>
  <dd><%= @cliente.uf %></dd>
  <dt>Email:</dt>
  <dd><%= @cliente.email %></dd>
  <dt>Codcidade ibge:</dt>
  <dd><%= @cliente.codcidade_ibge %></dd>
  <dt>Observações:</dt>
  <dd><%= @cliente.observacoes %></dd>
</dl>