config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :icms
  resources :cfop
  resources :terceiros
  resources :contas_pag
  resources :vendedores
  resources :contas_rec
  resources :plano_contas
  resources :administradores
  resources :transportadoras
  resources :localizacao_estoques
  resources :movimento_estoques, only: [:index]

  mount Sidekiq::Web => '/sidekiq'

  resources :estoques, only: %i[index show] do
    collection do
      post 'importar'

      scope module: 'estoques' do
        resources :reposicoes, only: %i[new create]
        resources :ajustes, :baixas, only: %i[new create]
      end
    end
  end

  resources :empresas do
    get 'configuracoes', on: :collection
  end
  
  resources :orcamentos do
    resources :orcamento_itens
  end

  resources :nota_fiscais do
    get 'observacoes', on: :member

    resources :gerar_nota_fiscais, only: [:gerar_nota] do
      get 'gerar_nota', on: :collection
    end

    resources :nota_fiscal_itens
    resources :nota_fiscal_duplicatas, only: %i[new create]
  end

  resources :produtos do
    post 'importar', on: :collection
  end

  resources :clientes do
    post 'importar', on: :collection
    get 'observacoes', on: :member

    resources :cliente_contatos
  end

  resources :fornecedores do
    post 'importar', on: :collection
    get 'observacoes', on: :member
  end

  resources :importacoes do
    collection do
      get 'clientes'
      get 'produtos'
      get 'estoques'
      get 'fornecedores'
    end
  end

  root to: 'home#index'

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

  #get "/orcamentos/relatorio", to: "orcamentos#relatorio"  
  #get "/orcamentos/relatorio", to: "orcamento#relatorio" 
  #get "relatorio", to: "orcamento#relatorio"
  #
  #resources :orcamentos
end

app/models/cliente_contato.rb
class ClienteContato < ApplicationRecord
  belongs_to :cliente
end

app/controllers/cliente_contatos_controller.rb
class ClienteContatosController < ApplicationController
  before_action :set_cliente_contato, only: %i[ show edit update destroy ]
  before_action :set_cliente

  def index
    @cliente_contatos = @cliente.contatos
  end

  def show
  end

  def new
    @cliente_contato = @cliente.contatos.new
  end

  def edit
  end

  def create
    @cliente_contato = @cliente.contatos.build(cliente_contato_params)

    respond_to do |format|
      if @cliente_contato.save
        format.html { redirect_to cliente_cliente_contatos_url(@cliente), notice: "Cliente contato was successfully created." }
        format.json { render :show, status: :created, location: @cliente_contato }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente_contato.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cliente_contato.update(cliente_contato_params)
        format.html { redirect_to cliente_cliente_contatos_url(@cliente), notice: "Cliente contato was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente_contato }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente_contato.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cliente_contato.destroy

    respond_to do |format|
      format.html { redirect_to cliente_cliente_contatos_url(@cliente), notice: "Cliente contato was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_cliente_contato
      @cliente_contato = ClienteContato.find(params[:id])
    end

    def set_cliente
      @cliente = Cliente.find(params[:cliente_id])     
    end

    def cliente_contato_params
      params.require(:cliente_contato).permit(:cliente_id, :nome, :telefone, :email, :cargo, :departamento)
    end
end

app/helpers/cliente_contatos_helper.rb
module ClienteContatosHelper
end

app/views/cliente_contatos/_form.html copy.erb
<%= form_for([@cliente, @cliente_contato], html: { class: "form-horizontal", role: "form" }) do |f| %>
    <% if @cliente_contato.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os campos abaixo:</h4>

      <ul>
      <% @cliente_contato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :cliente, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cliente, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :telefone, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :telefone, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cargo, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cargo, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :departamento, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :departamento, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/cliente_contatos/_form.html.erb
<%= form_for([@cliente, @cliente_contato], html: { class: "form-horizontal", role: "form" }) do |f| %>
    <% if @cliente_contato.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os campos abaixo:</h4>

      <ul>
      <% @cliente_contato.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :telefone, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :telefone, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cargo, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cargo, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :departamento, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :departamento, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/cliente_contatos/edit.html.erb
<h3>Contatos do Cliente</h3>

<h4><%= @cliente.id %> - <%= @cliente.nome%></h4>

<div class="page-header">
  <%= link_to cliente_cliente_contatos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @clienes_cliente_contato, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h3>Alteração</h3>
</div>

<%= render 'form' %>

app/views/cliente_contatos/index.html.erb
<h3>Contatos do Cliente</h3>
<h4><%= @cliente.id %> - <%= @cliente.nome%></h4>
<div class="page-header">
  <%= link_to new_cliente_cliente_contato_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <%= link_to edit_cliente_path(@cliente), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h2>Lista</h2>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Telefone</th>
        <th>Email</th>
        <th>Cargo</th>
        <th>Departamento</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= content_tag_for(:tr, @cliente_contatos) do |cliente_contato| %>
        <td><%= cliente_contato.nome %></td>
        <td><%= cliente_contato.telefone %></td>
        <td><%= cliente_contato.email %></td>
        <td><%= cliente_contato.cargo %></td>
        <td><%= cliente_contato.departamento %></td>
        <td><%= link_to 'Mostrar', cliente_cliente_contato_path(@cliente, cliente_contato) %></td>
        <td><%= link_to 'Editar', edit_cliente_cliente_contato_path(@cliente, cliente_contato) %></td>
        <td><%= link_to 'Apagar', cliente_cliente_contato_path(@cliente, cliente_contato), method: :delete, data: { confirm: 'Confirma ?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cliente_contatos/new.html.erb
<h2>Contato do Cliente</h2>

<h4><%= @cliente.id %> - <%= @cliente.nome%></h4>
  
<div class="page-header">
  <%= link_to cliente_cliente_contatos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h2>Inclusão</h2>
</div>

<%= render 'form' %>

app/views/cliente_contatos/show.html.erb
<h3>Contatos do Cliente</h3>

<h4><%= @cliente.id %> - <%= @cliente.nome%></h4>

<div class="page-header">
  <%= link_to cliente_cliente_contatos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_cliente_cliente_contato_path(@cliente_contato), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h2>Mostrar</h2>
</div>

<dl class="dl-horizontal">
  <dt>Cliente:</dt>
  <dd><%= @cliente_contato.cliente %></dd>
  <dt>Nome:</dt>
  <dd><%= @cliente_contato.nome %></dd>
  <dt>Telefone:</dt>
  <dd><%= @cliente_contato.telefone %></dd>
  <dt>Email:</dt>
  <dd><%= @cliente_contato.email %></dd>
  <dt>Cargo:</dt>
  <dd><%= @cliente_contato.cargo %></dd>
  <dt>Departamento:</dt>
  <dd><%= @cliente_contato.departamento %></dd>
</dl>