config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :icms
  resources :cfop
  resources :terceiros
  resources :contas_pag
  resources :vendedores
  resources :contas_rec
  resources :plano_contas
  resources :administradores
  resources :transportadoras
  resources :localizacao_estoques
  resources :movimento_estoques, only: [:index]

  mount Sidekiq::Web => '/sidekiq'

  resources :estoques, only: %i[index show] do
    collection do
      post 'importar'

      scope module: 'estoques' do
        resources :reposicoes, only: %i[new create]
        resources :ajustes, :baixas, only: %i[new create]
      end
    end
  end

  resources :empresas do
    get 'configuracoes', on: :collection
  end
  
  resources :orcamentos do
    resources :orcamento_itens
  end

  resources :nota_fiscais do
    get 'observacoes', on: :member

    resources :gerar_nota_fiscais, only: [:gerar_nota] do
      get 'gerar_nota', on: :collection
    end

    resources :nota_fiscal_itens
    resources :nota_fiscal_duplicatas, only: %i[new create]
  end

  resources :produtos do
    post 'importar', on: :collection
  end

  resources :clientes do
    post 'importar', on: :collection
    get 'observacoes', on: :member

    resources :cliente_contatos
  end

  resources :fornecedores do
    post 'importar', on: :collection
    get 'observacoes', on: :member
  end

  resources :importacoes do
    collection do
      get 'clientes'
      get 'produtos'
      get 'estoques'
      get 'fornecedores'
    end
  end

  root to: 'home#index'

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

  #get "/orcamentos/relatorio", to: "orcamentos#relatorio"  
  #get "/orcamentos/relatorio", to: "orcamento#relatorio" 
  #get "relatorio", to: "orcamento#relatorio"
  #
  #resources :orcamentos
end

app/models/contas_rec.rb
class ContasRec < ApplicationRecord
  belongs_to :cliente
  belongs_to :plano_conta, optional: true
  belongs_to :empresa

  has_many :contas_rec_parcelas, dependent: :delete_all
end

app/controllers/contas_rec_controller.rb
class ContasRecController < ApplicationController
  before_action :set_contas_rec, only: %i[show edit update destroy]

  def index
    @contas_rec = empresa.contas_rec

    # paginação na view index (lista)
    options = { page: params[:page] || 1, per_page: 50 }
    @contas_rec = @contas_rec.paginate(options)
  end

  def show; end

  def new
    @contas_rec = ContasRec.new
  end

  def edit; end

  def create
    @contas_rec = ContasRec.new(contas_rec_params)
    @contas_rec.empresa_id = @adm.empresa.id

    respond_to do |format|
      if @contas_rec.save
        save_contas_rec_parcelas
        format.html { redirect_to @contas_rec, notice: 'Contas a Receber Cadastrado' }
        format.json { render :show, status: :created, location: @contas_rec }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contas_rec.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contas_rec.update(contas_rec_params)
        save_contas_rec_parcelas
        format.html { redirect_to @contas_rec, notice: 'Contas a Receber Alterado' }
        format.json { render :show, status: :ok, location: @contas_rec }
      else
        format.html { render :edit, status: :unprocessable_entity }
         format.json { render json: @contas_rec.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contas_rec.destroy
    respond_to do |format|
      format.html { redirect_to contas_rec_index_url, notice: 'Contas a Receber Excluído' }
      format.json { head :no_content }
    end
  end

  private

  def set_contas_rec
    @contas_rec = ContasRec.find(params[:id])
  end

  def save_contas_rec_parcelas
    if params[:contas_rec].present? && params[:contas_rec][:contas_rec_parcela].present?
      @contas_rec.contas_rec_parcelas.destroy_all
      params[:contas_rec][:contas_rec_parcela].each do |parcela|
        next unless parcela[:data_vencimento].present? || parcela[:data_recebimento].present?

        contas_rec_parcela = ContasRecParcela.new(
          data_vencimento: parcela[:data_vencimento],
          data_pagamento: parcela[:data_pagamento],
          valor_parcela: parcela[:valor_parcela],
          valor_juros_desconto: parcela[:valor_juros_desconto],
          documento: parcela[:documento],
          descricao: parcela[:descricao],
          contas_rec: @contas_rec
        )
        
        contas_rec_parcela.save!
      end
    end
  end

  def contas_rec_params
    params.require(:contas_rec).permit(:cliente_id, :plano_conta_id, :documento, :historico, :data_emissao,
                                       :valor_total)
  end
end

app/helpers/contas_rec_helper.rb
module ContasRecHelper
end

app/views/contas_rec/_form.html.erb
<%= form_for(@contas_rec, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @contas_rec.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os campos abaixo:</h4>

      <ul>
      <% @contas_rec.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="col-sm-1 control-label">Nº Lançamento</label>
    <div class="col-sm-2">
      <input class="form-control" type="text" data-behavior="id_cliente" id="id_cliente" disabled>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :clientes, 'Cliente', class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.select :cliente_id, Cliente.all.reorder("nome asc").collect { |cliente| ["#{cliente.nome} - #{cliente.bairro}", cliente.id] }, {:selected => @contas_rec.cliente_id, :include_blank => true}, {:class=> 'form-control', :onclick=>"informarCliente()"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :plano_contas, 'Plano de Contas', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.select :plano_conta_id, PlanoConta.all.reorder("conta asc").collect { |plano_conta| [plano_conta.conta, plano_conta.id] }, {:selected => @contas_rec.plano_conta_id, :include_blank => true}, {:class=> 'form-control'} %>
    </div>

    <%= f.label :documento, 'Documento', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :documento, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :historico, 'Histórico', class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :historico, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :data_emissao, 'Data de Emissão', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.date_field :data_emissao, class: "form-control" %>
    </div>

    <%= f.label :valor_total, 'Valor Total', class: "col-sm-1 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :valor_total, class: "form-control" %>
    </div>
  </div>
 
 <br><br>

  <h3>Parcelas</h3>
  <hr>
  <div id="conteudoContainer">
    <% @contas_rec.contas_rec_parcelas.each do |contas_rec_parcela| %>
      <div class="item" style="margin-bottom: 40px">
        <div class="form-group">
          <label class="col-sm-2 control-label">Data de Vencimento</label>
          <div class="col-sm-3">
            <input class="form-control" type="date" value="<%= contas_rec_parcela.data_vencimento.strftime("%Y-%m-%d") rescue "" %>" name="contas_rec[contas_rec_parcela][][data_vencimento]">
          </div>

          <label class="col-sm-2 control-label">Data de Recebimento</label>
          <div class="col-sm-3">
            <input class="form-control" type="date" value="<%= contas_rec_parcela.data_recebimento.strftime("%Y-%m-%d") rescue "" %>" name="contas_rec[contas_rec_parcela][][data_recebimento]">
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Valor</label>
          <div class="col-sm-3">
            <input class="form-control" type="text" value="<%= contas_rec_parcela.valor_parcela %>" name="contas_rec[contas_rec_parcela][][valor_parcela]">
          </div>

          <label class="col-sm-2 control-label">Valor Acréscimo/Desconto</label>
          <div class="col-sm-3">
            <input class="form-control" type="text" value="<%= contas_rec_parcela.valor_juros_desconto %>" name="contas_rec[contas_rec_parcela][][valor_juros_desconto]">
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Documento</label>
          <div class="col-sm-3">
            <input class="form-control" type="text" value="<%= contas_rec_parcela.documento %>" name="contas_rec[contas_rec_parcela][][documento]">
          </div>

          <label class="col-sm-2 control-label">Descrição</label>
          <div class="col-sm-3">
            <input class="form-control" type="text" value="<%= contas_rec_parcela.descricao %>" name="contas_rec[contas_rec_parcela][][descricao]">
          </div>
        </div>

        <hr>
      </div>
    <% end %>

    <div class="item" style="margin-bottom: 40px">
      <div class="form-group">
        <label class="col-sm-2 control-label">Data de Vencimento</label>
        <div class="col-sm-3">
          <input class="form-control" type="date" name="contas_rec[contas_rec_parcela][][data_vencimento]">
        </div>

        <label class="col-sm-2 control-label">Data de Recebimento</label>
        <div class="col-sm-3">
          <input class="form-control" type="date" name="contas_rec[contas_rec_parcela][][data_recebimento]">
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Valor</label>
        <div class="col-sm-3">
          <input class="form-control" type="text" name="contas_rec[contas_rec_parcela][][valor_parcela]">
        </div>

        <label class="col-sm-2 control-label">Valor Acréscimo/Desconto</label>
        <div class="col-sm-3">
          <input class="form-control" type="text" name="contas_rec[contas_rec_parcela][][valor_juros_desconto]">
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Documento</label>
        <div class="col-sm-3">
          <input class="form-control" type="text" name="contas_rec[contas_rec_parcela][][documento]">
        </div>

        <label class="col-sm-2 control-label">Descrição</label>
        <div class="col-sm-3">
          <input class="form-control" type="text" name="contas_rec[contas_rec_parcela][][descricao]">
        </div>
      </div>

      <hr>
    </div>
  </div>

  <div class="form-group" style="text-align: right;">
    <a href="javascript:;" onclick="app.contas_pag.mais();" class="btn btn-primary">Mais</a>
  </div>

  <hr>

  <div class="form-group">
    <div class="col-sm-1">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<div id="conteudoContainerTemplate" style="display: none">
  <div class="item" style="margin-bottom: 40px">
      <div class="form-group">
        <label class="col-sm-2 control-label">Data de Vencimento</label>
        <div class="col-sm-3">
          <input class="form-control" type="date" name="contas_rec[contas_rec_parcela][][data_vencimento]">
        </div>

        <label class="col-sm-2 control-label">Data de Recebimento</label>
        <div class="col-sm-3">
          <input class="form-control" type="date" name="contas_rec[contas_rec_parcela][][data_recebimento]">
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Valor</label>
        <div class="col-sm-3">
          <input class="form-control" type="text" name="contas_rec[contas_rec_parcela][][valor_parcela]">
        </div>

        <label class="col-sm-2 control-label">Valor Acréscimo/Desconto</label>
        <div class="col-sm-3">
          <input class="form-control" type="text" name="contas_rec[contas_rec_parcela][][valor_juros_desconto]">
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Documento</label>
        <div class="col-sm-3">
          <input class="form-control" type="text" name="contas_rec[contas_rec_parcela][][documento]">
        </div>

        <label class="col-sm-2 control-label">Descrição</label>
        <div class="col-sm-3">
          <input class="form-control" type="text" name="contas_rec[contas_rec_parcela][][descricao]">
        </div>
      </div>

      <hr>
    </div>
</div>

<script>
//Bloqueia a tecla Enter no campo de Input
$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});

$(document).on('keyup', '[data-behavior~=id_cliente]', function(event) {
  $("#contas_rec_cliente_id").val(`${$("input[data-behavior='id_cliente']").val()}`);
});

const informarCliente = () =>{
  let cliente_id = $("#contas_rec_cliente_id").val()
  $("#id_cliente").val(`${cliente_id}`); 
}

</script>

app/views/contas_rec/edit.html.erb
<h2>Contas a Receber</h2>

<div class="page-header">
  <%= link_to contas_rec_index_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @contas_rec, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h3>Alteração</h3>
</div>

<%= render 'form' %>

app/views/contas_rec/index.html copy.erb
<h2>Contas a Receber</h2>
<div class="page-header">
  <%= link_to new_contas_rec_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <h2>Lista</h2>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Cliente</th>
        <th>Documento</th>
        <th>Histórico</th>
        <th>Data Emissão</th>
        <th>Valor Total</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= content_tag_for(:tr, @contas_rec) do |contas_rec| %>
        <td><%= contas_rec.cliente.nome %></td>
        <td><%= contas_rec.documento %></td>
        <td><%= contas_rec.historico %></td>
        <td><%= contas_rec.data_emissao.strftime("%d/%m/%Y") rescue "" %></td>
        <td style="text-align: end;"><%= number_to_currency(contas_rec.valor_total) %></td>
        <td><%= link_to 'Mostrar', contas_rec %></td>
        <td><%= link_to 'Editar', edit_contas_rec_path(contas_rec) %></td>
        <td><%= link_to 'Apagar', contas_rec, method: :delete, data: { confirm: 'Confirma ?' } %></td>
        <td><%= link_to 'Itens', nota_fiscal_nota_fiscal_itens_path(nota_fiscal) %></td>
        <td><%= link_to 'Gerar Nota', gerar_nota_nota_fiscal_gerar_nota_fiscais_path(nota_fiscal), class: "btn btn-success", target: "blank" %></td>
        <td><%= link_to 'Mostrar', nota_fiscal, class: "btn btn-primary" %></td>
        <td><a href="javascript:window.location.assign('/nota_fiscais/<%=nota_fiscal.id%>/edit')" class="btn btn-warning">Editar</a></td>
        <td><%= link_to 'Apagar', nota_fiscal, method: :delete, data: { confirm: 'Confirma ?' }, class: "btn btn-danger" %></td>
      <% end %>
    </tbody>
  </table>
  <div class="apple_pagination">
    <%= will_paginate @contas_rec, :container => false %>
  </div>
</div>

app/views/contas_rec/index.html.erb
<h2>Contas a Receber</h2>
<div class="page-header">
  <%= link_to new_contas_rec_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <h2>Lista</h2>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Cliente</th>
        <th>Documento</th>
        <th>Histórico</th>
        <th>Data Emissão</th>
        <th>Valor Total</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= content_tag_for(:tr, @contas_rec) do |contas_rec| %>
        <td><%= contas_rec.cliente.nome %></td>
        <td><%= contas_rec.documento %></td>
        <td><%= contas_rec.historico %></td>
        <td><%= contas_rec.data_emissao.strftime("%d/%m/%Y") rescue "" %></td>
        <td style="text-align: end;"><%= number_to_currency(contas_rec.valor_total) %></td>
        <td><%= link_to 'Mostrar', contas_rec, class: "btn btn-primary" %></td>
        <td><a href="javascript:window.location.assign('/contas_rec/<%=contas_rec.id%>/edit')" class="btn btn-warning">Editar</a></td>
        <td><%= link_to 'Apagar', contas_rec, method: :delete, data: { confirm: 'Confirma Exclusão ?' }, class: "btn btn-danger" %></td>
      <% end %>
    </tbody>
  </table>
  <div class="apple_pagination">
    <%= will_paginate @contas_rec, :container => false %>
  </div>
</div>

app/views/contas_rec/new.html.erb
<h2>Contas a Receber</h2>

<div class="page-header">
  <%= link_to contas_rec_index_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h2>Inclusão</h2>
</div>

<%= render 'form' %>

app/views/contas_rec/show.html.erb
<h2>Contas a Receber</h2>

<div class="page-header">
  <%= link_to contas_rec_index_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_contas_rec_path(@contas_rec), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h2>Mostrar</h2>
</div>

<dl class="dl-horizontal">
  <dt>Cliente:</dt>
  <dd><%= @contas_rec.cliente %></dd>
  <dt>Plano de Contas</dt>
  <dd><%= @contas_rec.plano_conta %></dd>
  <dt>Documento:</dt>
  <dd><%= @contas_rec.documento %></dd>
  <dt>Historico:</dt>
  <dd><%= @contas_rec.historico %></dd>
  <dt>Data emissao:</dt>
  <dd><%= @contas_rec.data_emissao %></dd>
  <dt>Valor total:</dt>
  <dd><%= @contas_rec.valor_total %></dd>
</dl>