config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :icms
  resources :cfop
  resources :terceiros
  resources :contas_pag
  resources :vendedores
  resources :contas_rec
  resources :plano_contas
  resources :administradores
  resources :transportadoras
  resources :localizacao_estoques
  resources :movimento_estoques, only: [:index]

  mount Sidekiq::Web => '/sidekiq'

  resources :estoques, only: %i[index show] do
    collection do
      post 'importar'

      scope module: 'estoques' do
        resources :reposicoes, only: %i[new create]
        resources :ajustes, :baixas, only: %i[new create]
      end
    end
  end

  resources :empresas do
    get 'configuracoes', on: :collection
  end
  
  resources :orcamentos do
    resources :orcamento_itens
  end

  resources :nota_fiscais do
    get 'observacoes', on: :member

    resources :gerar_nota_fiscais, only: [:gerar_nota] do
      get 'gerar_nota', on: :collection
    end

    resources :nota_fiscal_itens
    resources :nota_fiscal_duplicatas, only: %i[new create]
  end

  resources :produtos do
    post 'importar', on: :collection
  end

  resources :clientes do
    post 'importar', on: :collection
    get 'observacoes', on: :member

    resources :cliente_contatos
  end

  resources :fornecedores do
    post 'importar', on: :collection
    get 'observacoes', on: :member
  end

  resources :importacoes do
    collection do
      get 'clientes'
      get 'produtos'
      get 'estoques'
      get 'fornecedores'
    end
  end

  root to: 'home#index'

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/sair', to: 'login#deslogar'

  #get "/orcamentos/relatorio", to: "orcamentos#relatorio"  
  #get "/orcamentos/relatorio", to: "orcamento#relatorio" 
  #get "relatorio", to: "orcamento#relatorio"
  #
  #resources :orcamentos
end

app/models/plano_conta.rb
class PlanoConta < ApplicationRecord
  belongs_to :empresa
end

app/controllers/plano_contas_controller.rb
class PlanoContasController < ApplicationController
  before_action :set_plano_conta, only: %i[show edit update destroy]

  def index
    @plano_contas = empresa.plano_contas

    options = { page: params[:page] || 1, per_page: 50 }
    @plano_contas = @plano_contas.paginate(options)
  end

  def show; end

  def new
    @plano_conta = PlanoConta.new
  end

  def edit; end

  def create
    @plano_conta = PlanoConta.new(plano_conta_params)
    @plano_conta.empresa_id = @adm.empresa.id

    respond_to do |format|
      if @plano_conta.save
        format.html { redirect_to @plano_conta, notice: 'Plano conta Cadastrado' }
        format.json { render :show, status: :created, location: @plano_conta }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plano_conta.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @plano_conta.update(plano_conta_params)
        format.html { redirect_to @plano_conta, notice: 'Plano conta Alterado' }
        format.json { render :show, status: :ok, location: @plano_conta }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plano_conta.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @plano_conta.destroy
    respond_to do |format|
      format.html { redirect_to plano_contas_url, notice: 'Plano conta Excluído' }
      format.json { head :no_content }
    end
  end

  private

  def set_plano_conta
    @plano_conta = PlanoConta.find(params[:id])
  end

  def plano_conta_params
    params.require(:plano_conta).permit(:conta, :descricao, :grau)
  end
end

app/helpers/plano_contas_helper.rb
module PlanoContasHelper
end

app/views/plano_contas/_form.html.erb
<%= form_for(@plano_conta, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @plano_conta.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os campos abaixo:</h4>

      <ul>
      <% @plano_conta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :conta, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :conta, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descricao, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :descricao, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :grau, class: "col-sm-1 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :grau, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-1">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<script>
//Bloqueia a tecla Enter no campo de Input
$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});

</script>

app/views/plano_contas/edit.html.erb
<h2>Plano de Contas</h2>

<div class="page-header">
  <%= link_to plano_contas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @plano_conta, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h3>Alteração</h3>
</div>

<%= render 'form' %>

app/views/plano_contas/index.html.erb
<h2>Plano de Contas</h2>

<div class="page-header">
  <%= link_to new_plano_conta_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <h2>Lista</h2>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Conta</th>
            <th>Descrição</th>
            <th>Grau</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @plano_contas) do |plano_conta| %>
            <td><%= plano_conta.conta %></td>
            <td><%= plano_conta.descricao %></td>
            <td><%= plano_conta.grau %></td>
            <td><%= link_to 'Mostrar', plano_conta %></td>
        <td><%= link_to 'Editar', edit_plano_conta_path(plano_conta) %></td>
        <td><%= link_to 'Apagar', plano_conta, method: :delete, data: { confirm: 'Confirma ?' } %></td>
      <% end %>
    </tbody>
  </table>

  <div class="apple_pagination">
    <%= will_paginate @plano_contas, :container => false %>
  </div>    
</div>

app/views/plano_contas/new.html.erb
<h2>Plano de Contas</h2>

<div class="page-header">
  <%= link_to plano_contas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h2>Inclusão</h2>
</div>

<%= render 'form' %>

app/views/plano_contas/show.html.erb
<h2>Plano de Contas</h2>

<div class="page-header">
  <%= link_to plano_contas_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_plano_conta_path(@plano_conta), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h2>Mostrar</h2>
</div>

<dl class="dl-horizontal">
  <dt>Conta:</dt>
  <dd><%= @plano_conta.conta %></dd>
  <dt>Descricao:</dt>
  <dd><%= @plano_conta.descricao %></dd>
  <dt>Grau:</dt>
  <dd><%= @plano_conta.grau %></dd>
</dl>